// Code generated by MockGen. DO NOT EDIT.
// Source: bookReadingNote/aMicroservicesPatterns/code/chapter3/grpcExample/helloworld/helloworld/google.golang.org/grpc/examples/helloworld/helloworld (interfaces: GreeterClient)

// Package mock_helloworld is a generated GoMock package.
package mock_helloworld

import (
	helloworld "bookReadingNote/aMicroservicesPatterns/code/chapter3/grpcExample/helloworld/helloworld/google.golang.org/grpc/examples/helloworld/helloworld"
	context "context"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	reflect "reflect"
)

// MockGreeterClient is a mock of GreeterClient interface
type MockGreeterClient struct {
	ctrl     *gomock.Controller
	recorder *MockGreeterClientMockRecorder
}

// MockGreeterClientMockRecorder is the mock recorder for MockGreeterClient
type MockGreeterClientMockRecorder struct {
	mock *MockGreeterClient
}

// NewMockGreeterClient creates a new mock instance
func NewMockGreeterClient(ctrl *gomock.Controller) *MockGreeterClient {
	mock := &MockGreeterClient{ctrl: ctrl}
	mock.recorder = &MockGreeterClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGreeterClient) EXPECT() *MockGreeterClientMockRecorder {
	return m.recorder
}

// SayHello mocks base method
func (m *MockGreeterClient) SayHello(arg0 context.Context, arg1 *helloworld.HelloRequest, arg2 ...grpc.CallOption) (*helloworld.HelloReply, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SayHello", varargs...)
	ret0, _ := ret[0].(*helloworld.HelloReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SayHello indicates an expected call of SayHello
func (mr *MockGreeterClientMockRecorder) SayHello(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SayHello", reflect.TypeOf((*MockGreeterClient)(nil).SayHello), varargs...)
}

// SayHelloAgain mocks base method
func (m *MockGreeterClient) SayHelloAgain(arg0 context.Context, arg1 *helloworld.HelloAgainRequest, arg2 ...grpc.CallOption) (*helloworld.HelloAgainReply, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SayHelloAgain", varargs...)
	ret0, _ := ret[0].(*helloworld.HelloAgainReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SayHelloAgain indicates an expected call of SayHelloAgain
func (mr *MockGreeterClientMockRecorder) SayHelloAgain(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SayHelloAgain", reflect.TypeOf((*MockGreeterClient)(nil).SayHelloAgain), varargs...)
}
